apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo-ops
  name: demo-ops
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 32000
  selector:
    app: demo-ops
status:
  loadBalancer: {}
