---
- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Adding hostname to hosts file
      lineinfile:
        path: "/etc/hosts"
        regexp: '^127\.0\.0\.1'
        line: "127.0.0.1  localhost demo-ops"

    - name: Changing hostname
      hostname:
        name: "demo-ops"

    - name: "Adding user"
      user:
        name: "demo"

    - name: Sysctl rpoduction settings
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        sysctl_set: yes
        reload: yes
      loop:
        - { name: "fs.file-max", value: "2097152" }
        - { name: "vm.swappiness", value: "0" }
        - { name: "vm.dirty_ratio", value: "80" }
        - { name: "vm.dirty_background_ratio", value: "5" }
        - { name: "net.core.somaxconn", value: "65365" }
        - { name: "net.core.netdev_max_backlog", value: "8096" }
        - { name: "net.core.rmem_max", value: "16777216" }
        - { name: "net.core.wmem_max", value: "16777216" }
        - { name: "net.ipv4.tcp_wmem", value: "4096 12582912 16777216" }
        - { name: "net.ipv4.tcp_rmem", value: "4096 12582912 16777216" }
        - { name: "net.ipv4.tcp_tw_recycle", value: "1" }
        - { name: "net.ipv4.tcp_tw_reuse", value: "1" }
        - { name: "net.ipv4.tcp_rfc1337", value: "1" }
        - { name: "vm.overcommit_memory", value: "1" }
    
    - name: Disabling Transparent Huge packages
      shell: "echo never > /sys/kernel/mm/transparent_hugepage/enabled"

    - name: Transparent huge pages rc.local entry
      lineinfile:
        line: "echo never > /sys/kernel/mm/transparent_hugepage/enabled"
        path: /etc/rc.local

    - name: Change permissions of /etc/rc.local
      file:
        path: /etc/rc.local
        mode: "0777"

    - name: Setting timezone
      timezone:
        name: "Asia/Kolkata"

    - name: Adding Required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - "apt-transport-https"
        - "ca-certificates"
        - "curl"
        - "gnupg-agent"
        - "software-properties-common"

    - name: Add Docker s official GPG key
      remote_user: ubuntu
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adding the repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present
        update_cache: yes

    - name: Installing docker-ce
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - "docker-ce"
        - "docker-ce-cli"
        - "containerd.io"

    - name: Configuring the docker daemon
      copy:
        src: "daemon.json"
        dest: "/etc/docker/daemon.json"

    - name: Starting and enabling docker service
      service:
        name: docker
        state: restarted
        enabled: yes

    - name: Installing Docker-compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-Linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: "u+x,g+x"

    - name: Building the docker image
      shell: "docker-compose -f /etc/demo-ops/docker-compose.yaml build"

    - name: Starting the APP
      shell: "docker-compose -f /etc/demo-ops/docker-compose.yaml up -d"

    - name: Application is deployed
      debug: msg="Please open http://127.0.0.1:8000"
