# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "192.168.50.4"
  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
    vb.cpus = 2
    vb.memory = "2048"
  end
  config.vm.synced_folder "../demo-ops/", "/etc/demo-ops"
  config.vm.synced_folder "app_yamls/", "/etc/app_yamls"
  config.vm.provision :shell, :path => "k8s.sh"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "k8s-deploy.yaml"
  end
end
